### ISSUE TITLE
2nd line isn't shown when using layout_height="wrap_content"

### ISSUE THREAD

**Issue by loeschg** [ApmeM/android-flowlayout#31]
The following doesn't wrap correctly. It shows only what appears on the first line and truncates the rest. If I set an explicit height, it shows correctly.

                <org.apmem.tools.layouts.FlowLayout
                    android:id="@+id/review_scores_container"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="@dimen/spacing_small"
                    android:layout_marginLeft="@dimen/spacing_large"
                    android:layout_marginRight="@dimen/spacing_large"
                    app:orientation="horizontal"
                    >
                    <TextView
                        android:id="@+id/review_service_score"
                        tools:text="Some Text Some Text"
                        style="@style/MyStyle"
                        />
                    <TextView
                        android:id="@+id/review_responsiveness_score"
                        tools:text="Some Text Some Text"
                        style="@style/MyStyle"
                        />
                    <TextView
                        android:id="@+id/review_professionalism_score"
                        tools:text="Some Text Some Text"
                        style="@style/MyStyle"
                        />
                    <TextView
                        android:id="@+id/review_value_score"
                        tools:text="Some Text Some Text"
                        style="@style/MyStyle"
                        />
                    <TextView
                        android:id="@+id/review_flexibility_score"
                        tools:text="Some Text Some Text"
                        style="@style/MyStyle"
                        />
                </org.apmem.tools.layouts.FlowLayout>

**Comment by ApmeM** [comment]
Hi,

Sorry for late answer. I had no time to check this issue.
I have found, that I mix width and height modes in one 'switch', and did not check layout height property at all. 
Please use latest version from maven (1.8) or latest commit from this repository.
Thanks.

**Comment by loeschg** [comment]
Awesome. Thanks!
