### ISSUE TITLE
android:background fails with NPE

### ISSUE THREAD

**Issue by Sicness** [ApmeM/android-flowlayout#34]
Just try to add background color and you get java.lang.NullPointerException.
Pretty sadly...

**Comment by ApmeM** [comment]
Can you try to use latest commit. it is fixed there but not pushed to maven yet.

**Comment by Sicness** [comment]
Sure, but not sure when yet... I think you are able to check it out by your self ;)

**Comment by ApmeM** [comment]
I have uploaded latest commit to maven central. Please use latest version 1.7
