### ISSUE TITLE
Error:No such property: ossrhUsername for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

### ISSUE THREAD

**Issue by leo-plus** [ApmeM/android-flowlayout#37]
When i import project into AndroidStudio, it  promote this in "Messege" console.

**Comment by yrom** [comment]
you have not define these property: `ossrhUsername` and `ossrhPassword`

a simple fix is at [maven_push.gradle line 13](https://github.com/ApmeM/android-flowlayout/blob/master/libraries/layouts/maven_push.gradle#L13), call `hasProperty()` first
```groovy
authentication(userName: hasProperty('ossrhUsername')?ossrhUsername:'', password: hasProperty('ossrhPassword')?ossrhPassword:'')
```
same as [line 17](https://github.com/ApmeM/android-flowlayout/blob/master/libraries/layouts/maven_push.gradle#L17)

**Comment by ApmeM** [comment]
I have added your solution to the repository.

**Comment by vans88** [comment]
when I  replace " authentication(userName: ossrhUsername, password: ossrhPassword)" ---,osdetector-gradle-plugin/build.gradle line num:83-----with the above content . I am getting the following error:

:signArchives (Thread[main,5,main]) completed. Took 0.234 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signArchives'.
> Cannot perform signing task ':signArchives' because it has no configured signatory

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 9.619 secs

**Comment by prankkelkar** [comment]
> when I replace " authentication(userName: ossrhUsername, password: ossrhPassword)" ---,osdetector-gradle-plugin/build.gradle line num:83-----with the above content . I am getting the following error:
> 
> :signArchives (Thread[main,5,main]) completed. Took 0.234 secs.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':signArchives'.
>   > Cannot perform signing task ':signArchives' because it has no configured signatory
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 2 mins 9.619 secs

Even i am facing same issue. Any help would be appreciated.

**Comment by prankkelkar** [comment]
@vans88 Try this instead https://github.com/SudoPlayGames/Joise/issues/7#issuecomment-154736456
