### ISSUE TITLE
Failed to resolve:org.apmen.tools.layouts:1.8

### ISSUE THREAD

**Issue by timyu000** [ApmeM/android-flowlayout#44]
![k7s3_ rqmkm k_o uut 7](https://cloud.githubusercontent.com/assets/5511736/7154219/2e0d4b92-e386-11e4-8c44-4df56ebf24a8.jpg)

I add [compile 'org.apmem.tools:layouts:1.8@aar'] as a dependency

**Comment by asardari** [comment]
Try:
compile 'org.apmem.tools:layouts:1.8'

**Comment by vleango** [comment]
I had to clean my project to get it to work.
Build > Clean Project

**Comment by squeeish** [comment]
1.9 is not working as well.

**Comment by ApmeM** [comment]
are you sure you have added this code into your gradle file:

    repositories {
        mavenCentral()
    }

I have tried it and run gradle build, and after that I got those files downloaded correctly (checked with version 1.9 and 1.8):

    Download https://repo1.maven.org/maven2/org/apmem/tools/layouts/1.8/layouts-1.8.pom
    Download https://repo1.maven.org/maven2/org/apmem/tools/layouts/1.8/layouts-1.8.aar
    :app:preBuild UP-TO-DATE
    :app:preDebugBuild UP-TO-DATE
