### ISSUE TITLE
Difficult to extend functionality with subclasses.

### ISSUE THREAD

**Issue by DavidDTA** [ApmeM/android-flowlayout#50]
None of the logic for how the children will be laid out is visible to subclasses.  Are there objections to making the lines member protected?

**Comment by ApmeM** [comment]
Not sure what do you mean by lines member.
After onMeasure method all properties to find view location is stored in LayoutParams class.
Please see onLayout method to check how this position will be calculated.
LineDefinition list is not available outside of onMeasure as it is not exists and will be re-calculated next time onMeasure will be called.

**Comment by hospitalitarian** [comment]
You're right.  My original thinking is that it would be possible to modify the list of line definitions before the children's layout parameters were populated.  This issue was mainly because of how I originally tried to solve the other two issues I opened.

**Comment by hospitalitarian** [comment]
I've just come across the original reason for opening this issue.  We have a `LinedFlowLayout` which draws a line at the bottom of each row in the layout.  At present, we have to determine line positions via dead reckoning, but access to `lines` would allow us to draw the lines in a robust way.
