### ISSUE TITLE
FlowLayout does not respect relative gravity.

### ISSUE THREAD

**Issue by hospitalitarian** [ApmeM/android-flowlayout#52]
`start` is always treated as `left` and `end` is always treated as `right`

**Comment by ApmeM** [comment]
Relative gravity was added to flow layout.
BTW in case of vertical orientation and Relative gravity 
- START and END (which is actually relative bit + left and relative bit + right) become top and bottom (and it is ok), 
- TOP and BOTTOM (which does not have relative bit) become left and right (this is ok, but can be unclear at the beginning).
