### ISSUE TITLE
Full justification

### ISSUE THREAD

**Issue by ryandt** [ApmeM/android-flowlayout#54]
Are there any plans to support full justification alignment? Has anyone worked out a way to implement full justification into a FlowLayout and would be willing to share thoughts/findings?

Full justification example: https://upload.wikimedia.org/wikipedia/commons/d/d9/State_of_the_union_word_clouds.png

**Comment by ApmeM** [comment]
As I understand your question you can use Gravity.FILL for this behavior.
Did you try it?
