### ISSUE TITLE
Views cut off when using all-side margins

### ISSUE THREAD

**Issue by maniac103** [ApmeM/android-flowlayout#58]
As mentioned in the subject, views are (or may be) cut off at the end of each line when using all-side (top/bottom/left/right) margins.
This can be reproduced by modifying the example app layout like this: http://pastebin.com/dvNpbrqz

**Comment by ApmeM** [comment]
Sorry, your link says:
"This page has been removed!"

**Comment by maniac103** [comment]
OK, another try: http://fpaste.org/268402/24929931/

**Comment by ApmeM** [comment]
Aha, thanks.
Now I can see the problem, ok, will check what I can do.

**Comment by ApmeM** [comment]
I have found the problem - I forgot to take maring of last element into account.
It is fixed in latest commit. please check.
