### ISSUE TITLE
java.lang.IllegalArgumentException: Called attach on a child which is not detached

### ISSUE THREAD

**Issue by zourb** [ApmeM/android-flowlayout#60]
When i clicked the MANAGER TAB in the demo, i got crash stack like below.

10-20 12:32:01.470 7638-7638/? E/AndroidRuntime: FATAL EXCEPTION: main
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime: Process: org.apmem.tools.example, PID: 7638
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime: java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{a66dbff position=0 id=-1, oldPos=-1, pLpos:-1 no parent}
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$4.attachViewToParent(RecyclerView.java:587)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$LayoutManager.attachView(RecyclerView.java:6492)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$LayoutManager.attachView(RecyclerView.java:6507)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$LayoutManager.attachView(RecyclerView.java:6518)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at org.apmem.tools.layouts.FlowLayoutManager.onLayoutChildren(FlowLayoutManager.java:63)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2847)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3145)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
10-20 12:32:01.470 7638-7638/? E/AndroidRuntime:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java

**Comment by AtanL** [comment]
I got the same exception. It seems a bug of FlowLayoutManager.

**Comment by zeevQuickode** [comment]
I also get the same exception. Any idea on how to overcome this ?

@ApmeM

**Comment by eshkoliGilad** [comment]
Also got this exception, any idea on how to overcome this ?

@ApmeM

**Comment by Dev-iL** [comment]
@zourb @ghost @eshkoliGilad as mentioned by [niqo01](https://github.com/ApmeM/android-flowlayout/issues/59#issuecomment-144883302), changing `attachView` back to `addView` in `FlowLayoutManager` solves this issue (I can also confirm that this works). 

This may not be a "real fix" but rather a workaround.. Unfortunately I don't understand it well enough to tell which it is :)

**Comment by ApmeM** [comment]
Sorry for that. I reverted it on current master branch as well.
thanks @Dev-iL for this hint.
