### ISSUE TITLE
max line issue

### ISSUE THREAD

**Issue by jkinject** [ApmeM/android-flowlayout#62]
Hello!

i'm wondering if i can fix the max line of the widget?

i mean i don't want to extend more than 3 lines even if there are more items in the layout.

i just want to show items which are included in few lines and hide others.

i've tried fixing layout_height, but it didn't work. 

< org.apmem.tools.layouts.FlowLayout
    android:layout_width="match_parent"
    android:layout_height="40dp" >
        < ImageView android:layout_width="wrap_content" android:layout_height="30dp" android:src="@drawable/ic_addfollow" android:layout_margin="5dp" />
        < ImageView android:layout_width="wrap_content" android:layout_height="30dp" android:src="@drawable/ic_addfollow" android:layout_margin="5dp" />
        ...
        ... (omit)
        ...
</ org.apmem.tools.layouts.FlowLayout>

thank you for reading my question .

Regards.

**Comment by kishorejethava** [comment]
Same issue!!! 
Anyone has solution?

**Comment by zobnin** [comment]
Try my fork https://github.com/zobnin/android-flowlayout

**Comment by ApmeM** [comment]
Hi, @zobnin, can you create a pull request for your changes (but without readme.md changes) so I can merge them?

**Comment by ApmeM** [comment]
Pull request merged and tested.
It is available under master branch now.
Thanks @zobnin for this pull request.
