### ISSUE TITLE
HORIZONTAL SCROLL VIEW WITH FLOWLAYOUT

### ISSUE THREAD

**Issue by sharathyadhav1** [ApmeM/android-flowlayout#66]
I mean i need FLOWLAYOUTui inside hoizontal scroll view so the labels doesnt go to next line and scrolls inside horizontal scroll view,kindly let me know is it possible

and other thing is i should be able to set the orientation
<img width="431" alt="e183f768-9699-11e5-8d8b-b9456a222d08" src="https://cloud.githubusercontent.com/assets/8912909/11948233/15b525fe-a88b-11e5-91e8-131edfebe1e9.png">

**Comment by wightwulf1944** [comment]
I think the point of a FlowLayout is to wrap views into the next line. If you do not need to wrap views into the next line then you do not need a FlowLayout. You need a LinearLayout with horizontal orientation.

**Comment by ApmeM** [comment]
Yes, thank you @wightwulf1944 . Flow layout is designed to wrap content to new line if it is not fit to current line, so you don't need it in your case.
